language: python
python: 3.5
cache:
  directories:
    - $HOME/virtualenv/python3.5.3/
jobs:
  include:
    - stage: tests
      script: "coverage run -m unittest discover tests/unit" 1
      script: "coverage run -m unittest discover tests/journey" 2
    - stage: deploy
      script: "echo 'It works!'"
install:
  - python setup.py develop
  - pip install coveralls

after_success: coveralls

before_deploy: "echo 'Starting deploy to PyPI...'"
deploy:
  provider: pypi
  user: serenata
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    branch: master
after_deploy: "echo 'Deployment finished!'"
